import { ExpressValidatorWrapper } from "intellisolar-common";
import { TicketPriority, TicketStatus } from "../../../enums/ticket.enum";

export const getAllTicketsValidation = [
  ...ExpressValidatorWrapper.uuidValidator([
    {
      name: "assigned_to",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "assigned_by",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "created_by",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "updated_by",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "plant_id",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "component_type_id",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
    {
      name: "component_id",
      query: true,
      nullable: true,
      maxLength: 36,
      minLength: 36,
      message: "Invalid or missing ids.",
    },
  ]),
  ...ExpressValidatorWrapper.numberValidator([
    {
      name: "page",
      query: true,
      nullable: true,
      min: 1,
      message: "Page must be a positive number",
    },
    {
      name: "limit",
      query: true,
      nullable: true,
      min: 1,
      max: 100,
      message: "Limit must be a positive number between 1 and 100",
    },
    {
      name: "feedback_rating",
      query: true,
      nullable: true,
      min: 1,
      max: 5,
      message: "Feedback rating must be a number between 1 and 5",
    },
  ]),
  ...ExpressValidatorWrapper.stringValidator([
    {
      name: "search",
      query: true,
      nullable: true,
      minLength: 0,
      maxLength: 255,
      message: "Search term must be at most 255 characters",
    },
    {
      name: "sort_order",
      query: true,
      nullable: true,
      minLength: 3,
      maxLength: 4,
      message: "Sort order can be asc or desc.",
    },
    {
      name: "sort_by",
      query: true,
      nullable: true,
      minLength: 2,
      maxLength: 50,
      message: "Sort by must be at most 50 characters.",
    },
    {
      name: "plant_name",
      query: true,
      nullable: true,
      maxLength: 50,
      message: "Plant name must be a valid string",
    },
    {
      name: "component_type",
      query: true,
      nullable: true,
      maxLength: 50,
      message: `Component type must be a valid string`,
    },
    {
      name: "component_name",
      query: true,
      nullable: true,
      maxLength: 255,
      message: "Component name must be a valid string",
    },
    {
      name: "title",
      query: true,
      nullable: true,
      maxLength: 100,
      message: "Title must be a string with maximum 100 characters",
    },
    {
      name: "source",
      query: true,
      nullable: true,
      message: "Source must be a valid string",
    },
    {
      name: "status",
      query: true,
      nullable: true,
      customValidators: [
        (value: string) =>
          Object.values(TicketStatus).includes(value.trim() as TicketStatus),
      ],
      message: `Invalid status type must be in ${Object.values(TicketStatus).join(", ")}.`,
    },
    {
      name: "priority",
      query: true,
      nullable: true,
      customValidators: [
        (value: string) =>
          Object.values(TicketPriority).includes(
            value.trim() as TicketPriority,
          ),
      ],
      message: `Invalid priority type must be in ${Object.values(TicketPriority).join(", ")}.`,
    },
  ]),
  ...ExpressValidatorWrapper.dateValidator([
    {
      name: "resolved_at_start",
      query: true,
      nullable: true,
      message: "Resolved at start must be a valid ISO 8601 date.",
    },
    {
      name: "resolved_at_end",
      query: true,
      nullable: true,
      message: "Resolved at end must be a valid ISO 8601 date.",
    },
    {
      name: "created_at_start",
      query: true,
      nullable: true,
      message: "Created at start must be a valid ISO 8601 date.",
    },
    {
      name: "created_at_end",
      query: true,
      nullable: true,
      message: "Created at end must be a valid ISO 8601 date.",
    },
    {
      name: "updated_at_start",
      query: true,
      nullable: true,
      message: "Updated at start must be a valid ISO 8601 date.",
    },
    {
      name: "updated_at_end",
      query: true,
      nullable: true,
      message: "Updated at end must be a valid ISO 8601 date.",
    },
  ]),
  ...ExpressValidatorWrapper.booleanValidator([
    {
      name: "overdue",
      query: true,
      nullable: true,
      message: "Overdue must be a boolean value.",
    },
    {
      name: "unassigned",
      query: true,
      nullable: true,
      message: "Unassigned must be a boolean value.",
    },
    {
      name: "has_feedback",
      query: true,
      nullable: true,
      message: "Has_Feedback must be a boolean value.",
    },
  ]),
];
