export interface PlantRow {
    id: string;
    tenant_id: string;
    organization_id: string;
    plant_name: string;
    plant_type?: string | null;
    plant_category?: string | null;
    owner?: { id?: string; name?: string } | null;
    is_forecast: boolean;
    contact_person_name: string;
    contact_person_email: string;
    contact_person_phone?: string | null;
    contact_person_designation?: string | null;
    dc_capacity_kw?: number | null;
    ac_capacity_kw?: number | null;
    sanctioned_load_kw?: number | null;
    connected_load_kw?: number | null;
    grid_voltage_kv?: number | null;
    connection_point?: string | null;
    transformer_capacity_kva?: number | null;
    meter_number?: string | null;
    consumer_number?: string | null;
    feeder_name?: string | null;
    substation_name?: string | null;
    discom_name?: string | null;
    location_name?: string | null;
    address?: string | null;
    city?: string | null;
    district?: string | null;
    taluka?: string | null;
    state?: string | null;
    country?: string | null;
    pincode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
    elevation_m?: number | null;
    timezone?: string | null;
    grid_type?: string | null;
    net_metering?: boolean | null;
    commissioning_date?: Date | null;
    cod_date?: Date | null;
    ppa_rate?: number | null;
    ppa_escalation_percent?: number | null;
    ppa_duration_years?: number | null;
    revenue_type?: number | null;
    tariff_type?: string | null;
    expected_annual_generation_kwh?: number | null;
    expected_cuf_percent?: number | null;
    expected_pr_percent?: number | null;
    expected_yield_kwh_kwp?: number | null;
    module_json?: PlantModule[] | null;
    tilt_angle_degrees?: number | null;
    azimuth_angle_degrees?: number | null;
    orientation?: string | null;
    notify_users?: string[] | null;
    features?: string[] | null;
    is_active: boolean;
    is_commissioned: boolean;
    plant_image?: string | null;
    metadata?: Record<string, unknown> | null;
    tags?: string[] | null;
    tenant_name?: string | null;
    organization_name: string;
    created_by_name?: string | null;
    updated_by_name?: string | null;
    created_by: string;
    updated_by?: string | null;
    created_at: Date;
    updated_at?: Date | null;
};

export interface PlantModule {
    qty?: number | null;
    make?: string | null;
    model?: string | null;
    capacity_w?: number | null;
    technology?: string | null;
    efficiency_percent?: number | null;
}
